import { useState } from 'react';
import { Pressable, StyleSheet, Text } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import AppScreen from '@shared/ui/AppScreen'; import AppInput from '@shared/ui/AppInput'; import AppButton from '@shared/ui/AppButton'; import ScreenHeader from '@shared/ui/ScreenHeader'; import StatusBanner from '@shared/ui/StatusBanner';
import Routes from '@shell/navigation/routes'; import { identityApi, ApiError } from '@core/api'; import { useAppTheme } from '@shared/theme'; import { useI18n } from '@shared/i18n'; import { isEmail, isPassword } from '@shared/validation/formRules';

export default function RegisterStep2Screen() {
  const router = useRouter(); const params = useLocalSearchParams<{ username: string; name: string; lastName: string; phone: string }>(); const { t } = useI18n(); const { colors, spacing } = useAppTheme();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [accepted, setAccepted] = useState(false); const [submitted, setSubmitted] = useState(false); const [error, setError] = useState<string | null>(null); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(false);
  const valid = isEmail(email) && isPassword(password) && password === confirm && accepted;
  const submit = async () => { setSubmitted(true); if (!valid) return; setLoading(true); setError(null); setFieldErrors({}); try { const registration = await identityApi.createRegistration({ username: params.username, firstNames: params.name, lastNames: params.lastName, email: email.trim(), phone: params.phone, password, acceptedTerms: true }); await identityApi.issueRegistrationCode(registration.registrationRequestId, 'EMAIL'); router.replace({ pathname: Routes.verifyCode, params: { flow: 'registration', registrationRequestId: registration.registrationRequestId, channel: 'EMAIL', destination: email.trim(), phone: params.phone } }); } catch (cause) { const apiError = cause as ApiError; setFieldErrors(apiError.fields); setError(apiError.fields.email ?? apiError.fields.username ?? apiError.fields.firstNames ?? apiError.fields.lastNames ?? apiError.fields.phone ?? apiError.message ?? 'No fue posible crear la solicitud.'); } finally { setLoading(false); } };
  return <AppScreen><ScreenHeader canGoBack title={t('auth.personalTitle')} subtitle={t('auth.credentialsSubtitle')}/>{error ? <StatusBanner tone="danger" title="Revisa tus datos" message={error}/> : null}<AppInput label={t('auth.email')} value={email} onChangeText={(value) => { setEmail(value); setFieldErrors((current) => ({ ...current, email: '' })); }} keyboardType="email-address" autoCapitalize="none" error={fieldErrors.email || (submitted && !isEmail(email) ? t('validation.email') : undefined)}/><AppInput label={t('auth.password')} value={password} onChangeText={setPassword} secureTextEntry showPasswordToggle error={submitted && !isPassword(password) ? t('validation.password') : undefined}/><AppInput label={t('auth.confirmPassword')} value={confirm} onChangeText={setConfirm} secureTextEntry showPasswordToggle error={submitted && password !== confirm ? t('validation.passwordMatch') : undefined}/><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: accepted }} onPress={() => setAccepted(!accepted)} style={[styles.accept, { marginBottom: spacing.lg }]}><Ionicons name={accepted ? 'checkbox' : 'square-outline'} size={24} color={submitted && !accepted ? colors.danger : colors.primary}/><Text style={{ color: colors.textDark, flex: 1 }}>{t('auth.accept')}</Text></Pressable><AppButton title={t('auth.create')} onPress={() => void submit()} loading={loading}/></AppScreen>;
}
const styles = StyleSheet.create({ accept: { flexDirection: 'row', gap: 10, alignItems: 'flex-start' } });
